### ISSUE TITLE
KeyError: 'content-type' is being raised when reloading pages with images.

### ISSUE THREAD

**Issue by JoaoG250** [jadsonlucio/django-autorefresh#6]
https://github.com/jadsonlucio/django-autorefresh/blob/09fe7257d280c3fb4be8693f7eb7cd97595bff46/fresh/middleware.py#L45

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/fresh/middleware.py", line 96, in __call__
    return self.process_template_response(request, response)
  File "/usr/local/lib/python3.8/site-packages/fresh/middleware.py", line 45, in process_template_response
    mimetype = response.headers["content-type"]
  File "/usr/local/lib/python3.8/site-packages/django/utils/datastructures.py", line 316, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'

**Comment by JoaoG250** [comment]
PS: When hard reloading with Ctrl + F5 the exception is not raised.

**Comment by jadsonlucio** [comment]
@JoaoG250 fixed in branch  fix-content-type-error
